global:
  scrape_interval: 15s # Global default scrape interval
  evaluation_interval: 15s # Global default evaluation interval

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alert-manager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - prometheus:9090
  - job_name: node
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: plex
    static_configs:
      - targets:
        - plex-exporter:9000
  - job_name: graphite
    static_configs:
      - targets:
        - graphite-exporter:9108
