
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    # family: Iosevka
    family: "FuraCode Nerd Font"
    # family: "Source Code Pro"
    # style: Retina

  # The bold font face
  bold:
    # family: Iosevka
    family: "FuraCode Nerd Font"
    # family: "Source Code Pro"

  # The italic font face
  italic:
    # family: Iosevka
    family: "FuraCode Nerd Font"
    # family: "Source Code Pro"
    # style: "Medium Italic"

  # Point size of the font
  size: 14.0

# Live config reload (changes require restart)
live_config_reload: true

# cursorColor="#8da3b8"                                                                     
# cursorColor2="#202427"

# Colors
colors:
  # Default colours
  primary:
    background: '0x202427'
    foreground: '0x8da3b8'

  # Colors that should be used to draw the terminal cursor. If these are unset,
  # the cursor colour will be the inverse of the cell colour.
  # cursor:
  #   text: '0x2e2e2d'
  #   # text: '0x000000'
  #   cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x202427'
    red:     '0xeb6a58'
    green:   '0x49a61d'
    yellow:  '0x959721'
    blue:    '0x798fd7'
    magenta: '0xcd7b7e'
    cyan:    '0x4fa090'
    white:   '0x909294'

  # Bright colors
  bright:
    black:   '0x292b35'
    red:     '0xdb7824'
    green:   '0x00a854'
    yellow:  '0xad8e4b'
    blue:    '0x309dc1'
    magenta: '0xc874c2'
    cyan:    '0x1ba2a0'
    white:   '0x8da3b8'
