# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.kernelParams = ["console=ttyS0,19200n8"];
  boot.loader.grub.enable = true;
  boot.loader.grub.extraConfig = ''
    serial --speed=19200 --unit=0 --word=8 --parity=no --stop=1;
    terminal_input serial;
    terminal_output serial;
    insmod btrfs;
  '';

  boot.loader.grub.forceInstall = true;
  boot.loader.grub.devices = ["nodev"];
  #boot.loader.timeout = 10;
  boot.loader.systemd-boot.enable = false;

  boot.initrd.availableKernelModules = ["virtio_pci" "virtio_scsi" "ahci" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/sda";
    fsType = "btrfs";
    options = ["subvol=rootfs"];
  };

  fileSystems."/boot" = {
    device = "/dev/sda";
    fsType = "btrfs";
    options = ["subvol=boot"];
  };

  fileSystems."/nix" = {
    device = "/dev/sda";
    fsType = "btrfs";
    options = ["compress=zstd" "noatime" "subvol=nix"];
  };

  fileSystems."/data" = {
    device = "/dev/sda";
    fsType = "btrfs";
    options = ["compress=zstd" "subvol=data"];
  };

  fileSystems."/home" = {
    device = "/dev/sda";
    fsType = "btrfs";
    options = ["compress=zstd" "subvol=home"];
  };

  fileSystems."/partition-root" = {
    device = "/dev/sda";
    fsType = "btrfs";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = false;
  # networking.interfaces.enp0s5.useDHCP = lib.mkDefault true;
  networking.interfaces.eth0.useDHCP = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
