# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  ...
}: {
  services.fwupd.enable = true;
  time.hardwareClockInLocalTime = true;
  hardware.graphics.enable32Bit = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/13f4c197-72aa-4ce3-8945-6954b9073bf9";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/CED1-6282";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/efi/EFI/Linux" = {
    device = "/boot/EFI/Linux";
    options = ["bind"];
  };
  fileSystems."/efi/EFI/nixos" = {
    device = "/boot/EFI/nixos";
    options = ["bind"];
  };

  swapDevices = [];

  hardware.enableRedistributableFirmware = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
