#!/usr/bin/env sh

CONFIG=(

# global settings
mouse_follows_focus          off
focus_follows_mouse          off
window_origin_display        default
window_placement             second_child
window_topmost               off
window_shadow                off
window_opacity               off
window_opacity_duration      0.0
window_animation_duration    0.0
window_animation_framerate   60
active_window_opacity        1
normal_window_opacity        1.00
window_border                on
window_border_hidpi          on
window_border_blur           on
window_border_width          1
window_border_radius         10
active_window_border_color   0xFF88C0D0 #88C0D0
normal_window_border_color   0xFF434C5E #434C5E
insert_feedback_color        0xFFD75F5F #D75F5F

split_ratio                  0.50
auto_balance                 on
mouse_modifier               fn
mouse_action1                move
mouse_action2                resize

# general space settings
layout                       bsp
top_padding                  10
bottom_padding               10
left_padding                 10
right_padding                10
window_gap                   5

#external_bar                 all:52:0
)

yabai -m config "${CONFIG[@]}"

echo "yabai global configuration loaded."
