#!/usr/bin/env sh

# space names
yabai -m space 1 --label music
yabai -m space 2 --label chat
yabai -m space 3 --label personal_chat
yabai -m space 4 --label browser
yabai -m space 5 --label email
yabai -m space 6 --label tasks
yabai -m space 7 --label term
yabai -m space 8 --label books
yabai -m space 9 --label social
yabai -m space 10 --label windows10
yabai -m space 11 --label vbrowser

# space assignments
yabai -m rule --add app="^iTerm2$" space=term
yabai -m rule --add app="^Spotify$" space=music
yabai -m rule --add app="^Tweetbot$" space=music
yabai -m rule --add app="^Messages$" space=music
yabai -m rule --add app="^Slack$" space=chat
yabai -m rule --add app="^Chat$" space=chat
yabai -m rule --add app="^Element$" space=personal_chat
yabai -m rule --add app="^Discord$" space=personal_chat
yabai -m rule --add app="^Fantastical$" space=email
yabai -m rule --add app="^Mimestream$" space=email
#yabai -m rule --add app="^Boxy for Gmail$" space=email
#yabai -m rule --add app="^Boxy for Calendar$" space=email
yabai -m rule --add app="^Google Chrome$" space=browser
yabai -m rule --add app="^Google Chrome$" title="Chat - Google Chrome$" space=chat
yabai -m rule --add app="^Firefox$" space=browser
yabai -m rule --add app="^Bear$" space=tasks
yabai -m rule --add app="^Obsidian$" space=tasks
yabai -m rule --add app="^Spark$" space=social
yabai -m rule --add app="^Things$" space=tasks
yabai -m rule --add app="^Miro$" space=miro
yabai -m rule --add app="^Stream Deck$" space=miro
yabai -m rule --add app="^Reeder$" space=books
yabai -m rule --add app="^Kindle$" space=books
yabai -m rule --add app="^OBS$" space=windows10
yabai -m rule --add app="^Parallels Desktop$" space=windows10
yabai -m rule --add app="^Microsoft Edge$" space=windows10
yabai -m rule --add app="^Windows 10$" space=windows10

echo "yabai spaces configuration loaded."
