#!/usr/bin/env sh

CONFIG=(

# global settings
mouse_follows_focus          off
focus_follows_mouse          off
window_origin_display        default
window_placement             second_child
window_shadow                off
window_opacity               off
window_opacity_duration      0.0
active_window_opacity        1
normal_window_opacity        1.00

split_ratio                  0.50
auto_balance                 on
mouse_modifier               fn
mouse_action1                move
mouse_action2                resize

# general space settings
layout                       bsp
top_padding                  02
bottom_padding               05
left_padding                 05
right_padding                05
window_gap                   5

#external_bar                 all:52:0
)

yabai -m config "${CONFIG[@]}"

echo "yabai global configuration loaded."
