# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  services.fwupd.enable = true;
  hardware.enableRedistributableFirmware = true;
  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault false;
  # networking.interfaces.enp2s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp87s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp88s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp89s0.useDHCP = lib.mkDefault true;
  networking = {
    dhcpcd.enable = false;
    interfaces = {
      enp2s0f0np0.ipv4.addresses = [
        {
          address = "10.55.10.54";
          prefixLength = 24;
        }
      ];
      vlan2.ipv4.addresses = [
        {
          address = "10.55.20.24";
          prefixLength = 24;
        }
      ];
      vlan6.ipv4.addresses = [
        {
          address = "10.55.60.24";
          prefixLength = 24;
        }
      ];
    };
    defaultGateway = "10.55.10.1";
    nameservers = ["10.55.10.35"];
    vlans = {
      vlan2 = {
        id = 2;
        interface = "enp2s0f0np0";
      };
      vlan6 = {
        id = 6;
        interface = "enp2s0f0np0";
      };
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
